name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
    
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt3 App
        run: npm run build

      - name: Prepare deployment zip
        run: zip -r deploy.zip .

      - name: Upload deployment to server
        run: scp deploy.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DESTINATION }}

      - name: Unzip & deploy on server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.SSH_DESTINATION }}
            unzip -o deploy.zip
            rm deploy.zip
          EOF